name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ashutosh00710/github-readme-activity-graph@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output_filepath: profile-activity-graph.svg
          theme: react-dark
